# Generated by Django 5.0.1 on 2024-01-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompttext', models.TextField()),
                ('summarytext', models.TextField()),
                ('content', models.DecimalField(decimal_places=3, max_digits=10)),
                ('wording', models.DecimalField(decimal_places=3, max_digits=10)),
                ('responses', models.TextField(blank=True)),
            ],
        ),
    ]
